// AUTO-GENERATED by scripts/fetch-fanza-works.mjs — do not edit manually
// Last updated: 2026-05-28

export type Category = 'asmr' | 'ntr' | 'ts' | 'yuri' | 'ninpu' | 'hypno';

export const CATEGORY_LABELS: Record<Category, string> = {
  asmr:  'ASMR',
  ntr:   'NTR',
  ts:    'TS',
  yuri:  '百合',
  ninpu: '妊婦',
  hypno: '催眠',
};

export type Work = {
  id: string;
  title: string;
  circle: string;
  cv: string;
  category: Category;
  price: number;
  rating: number;
  tags: string[];
  description: string;
  affiliateUrl: string;
  thumbnailUrl: string;
};

export const works: Work[] = [
  {
    "id": "1",
    "title": "即おち！〜’city girls’〜脈なし女子を即堕ち催●→エモ系・彗ちゃん催●我慢でNTR失敗！？『いぎっ♪いぎだぐないっ♪』彼氏に通話で敗北実況！仰け反り涙の無様イキ♪",
    "circle": "上海飯店",
    "cv": "不明",
    "category": "ntr",
    "price": 1650,
    "rating": 5,
    "tags": [
      "寝取り・寝取られ・NTR",
      "中出し",
      "ASMR",
      "耳舐め",
      "潮吹き",
      "KU100"
    ],
    "description": "即おち！〜’city girls’〜脈なし女子を即堕ち催●→エモ系・彗ちゃん催●我慢でNTR失敗！？『いぎっ♪いぎだぐないっ♪』彼氏に通話で敗北実況！仰け反り涙の無様イキ♪",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_342043/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_342043/d_342043pl.jpg"
  },
  {
    "id": "2",
    "title": "いいなり女子マネージャーは野球部専用性処理係ASMR【KU100】",
    "circle": "アトリエTODO",
    "cv": "不明",
    "category": "asmr",
    "price": 770,
    "rating": 5,
    "tags": [
      "巨乳",
      "体操着・ブルマ",
      "中出し",
      "ASMR",
      "KU100",
      "学園もの"
    ],
    "description": "いいなり女子マネージャーは野球部専用性処理係ASMR【KU100】",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_564230/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_564230/d_564230pl.jpg"
  },
  {
    "id": "3",
    "title": "秘公開ASMRプラン〜推し配信者と秘密のオフパコえっち〜",
    "circle": "FANZA同人オリジナル",
    "cv": "不明",
    "category": "asmr",
    "price": 1155,
    "rating": 5,
    "tags": [
      "水着",
      "コスプレ",
      "中出し",
      "フェラ",
      "パイズリ",
      "超乳"
    ],
    "description": "秘公開ASMRプラン〜推し配信者と秘密のオフパコえっち〜",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_719942/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_719942/d_719942pl.jpg"
  },
  {
    "id": "4",
    "title": "国民的正統派アイドルの教え子巨乳JKが裏の顔で堕とす逆NTRケーカク〜 ファンの心を漬け込み担任教師を寝取る究極甘々快楽不倫SEX〜【ASMR/KU100】",
    "circle": "KleptoMania ［クレプトマニア］",
    "cv": "不明",
    "category": "ntr",
    "price": 1078,
    "rating": 5,
    "tags": [
      "制服",
      "学園もの",
      "寝取り・寝取られ・NTR",
      "アイドル・芸能人",
      "中出し",
      "フェラ"
    ],
    "description": "国民的正統派アイドルの教え子巨乳JKが裏の顔で堕とす逆NTRケーカク〜 ファンの心を漬け込み担任教師を寝取る究極甘々快楽不倫SEX〜【ASMR/KU100】",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_675672/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_675672/d_675672pl.jpg"
  },
  {
    "id": "5",
    "title": "排卵日に子作り懇願おほ声イグイグ妹ASMR Vol.02【KU100】自己肯定感低めボッチ系メンヘラ妹の麻季ちゃんのお話",
    "circle": "アトリエTODO",
    "cv": "不明",
    "category": "asmr",
    "price": 770,
    "rating": 5,
    "tags": [
      "巨乳",
      "中出し",
      "ラブラブ・あまあま",
      "義妹",
      "ASMR",
      "KU100"
    ],
    "description": "排卵日に子作り懇願おほ声イグイグ妹ASMR Vol.02【KU100】自己肯定感低めボッチ系メンヘラ妹の麻季ちゃんのお話",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_537885/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_537885/d_537885pl.jpg"
  },
  {
    "id": "6",
    "title": "【ODし過ぎてガンギマリおほ声でパキッちゃう系】承認欲求高めメンタルクソ雑魚 見えてる地雷のメンヘラ黒巳さんをただ幸せにするお話ASMR【KU100】",
    "circle": "アトリエTODO",
    "cv": "不明",
    "category": "asmr",
    "price": 924,
    "rating": 5,
    "tags": [
      "巨乳",
      "中出し",
      "ラブラブ・あまあま",
      "ASMR",
      "わからせ",
      "KU100"
    ],
    "description": "【ODし過ぎてガンギマリおほ声でパキッちゃう系】承認欲求高めメンタルクソ雑魚 見えてる地雷のメンヘラ黒巳さんをただ幸せにするお話ASMR【KU100】",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_589890/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_589890/d_589890pl.jpg"
  },
  {
    "id": "7",
    "title": "【4Kぬるぬるアニメ】ぬるぬるJKマ◯コ禁断の援○交際",
    "circle": "究極のあいどる",
    "cv": "不明",
    "category": "ntr",
    "price": 165,
    "rating": 5,
    "tags": [
      "動画・アニメーション",
      "音声付き",
      "寝取り・寝取られ・NTR",
      "中出し",
      "退廃・背徳・インモラル",
      "売春・援交"
    ],
    "description": "【4Kぬるぬるアニメ】ぬるぬるJKマ◯コ禁断の援○交際",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_302900/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/cg/d_302900/d_302900pl.jpg"
  },
  {
    "id": "8",
    "title": "【4Kぬるぬるアニメ】ぬちょぬちょと楽しみながらする、女子校生との援○交際",
    "circle": "究極のあいどる",
    "cv": "不明",
    "category": "ntr",
    "price": 165,
    "rating": 5,
    "tags": [
      "動画・アニメーション",
      "音声付き",
      "寝取り・寝取られ・NTR",
      "中出し",
      "退廃・背徳・インモラル",
      "売春・援交"
    ],
    "description": "【4Kぬるぬるアニメ】ぬちょぬちょと楽しみながらする、女子校生との援○交際",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_302894/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/cg/d_302894/d_302894pl.jpg"
  },
  {
    "id": "9",
    "title": "【KU100】強●オナホ女神 〜追放された復讐に満足するまで女神を中出しレ●プ〜",
    "circle": "生ハメ堕ち部★LACK",
    "cv": "不明",
    "category": "asmr",
    "price": 10,
    "rating": 5,
    "tags": [
      "ファンタジー",
      "巨乳",
      "フェラ",
      "イラマチオ",
      "焦らし",
      "ASMR"
    ],
    "description": "【KU100】強●オナホ女神 〜追放された復讐に満足するまで女神を中出しレ●プ〜",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_253560/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_253560/d_253560pl.jpg"
  },
  {
    "id": "10",
    "title": "【KU100】わからせオホ声催◯！ 〜彼氏持ちギャルに催●をかけて下品でひっくい喘ぎ声でイかせたら？〜",
    "circle": "スタジオりふれぼ",
    "cv": "不明",
    "category": "asmr",
    "price": 660,
    "rating": 5,
    "tags": [
      "学園もの",
      "ギャル",
      "巨乳",
      "中出し",
      "フェラ",
      "パイズリ"
    ],
    "description": "【KU100】わからせオホ声催◯！ 〜彼氏持ちギャルに催●をかけて下品でひっくい喘ぎ声でイかせたら？〜",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_221294/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_221294/d_221294pl.jpg"
  },
  {
    "id": "11",
    "title": "お小遣い欲しさに変態プレイを許容してくれる義理のお姉ちゃん",
    "circle": "うえぶんり",
    "cv": "不明",
    "category": "asmr",
    "price": 1100,
    "rating": 5,
    "tags": [
      "中出し",
      "義姉",
      "クール攻め",
      "ASMR",
      "手コキ",
      "ささやき"
    ],
    "description": "お小遣い欲しさに変態プレイを許容してくれる義理のお姉ちゃん",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_215807/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_215807/d_215807pl.jpg"
  },
  {
    "id": "12",
    "title": "添い寝フレンドと行く温泉旅行 -おもちゃえっちつき-【フォーリー】",
    "circle": "妄想研究所",
    "cv": "不明",
    "category": "asmr",
    "price": 1650,
    "rating": 5,
    "tags": [
      "和服・浴衣",
      "ラブラブ・あまあま",
      "実妹",
      "包茎"
    ],
    "description": "添い寝フレンドと行く温泉旅行 -おもちゃえっちつき-【フォーリー】",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_184987/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_184987/d_184987pl.jpg"
  },
  {
    "id": "13",
    "title": "弱ローターなら無限に当てれる説を立証？！絶頂超研究！電マで！バイブで！おしっこも！【バイノーラル、ASMR、フォーリーサウンド、実演音声、実演オナニー】",
    "circle": "ぼっちえっちLAB",
    "cv": "不明",
    "category": "asmr",
    "price": 539,
    "rating": 5,
    "tags": [
      "音声付き",
      "デモ・体験版あり",
      "巨乳",
      "バイブ",
      "オナニー",
      "放尿・お漏らし"
    ],
    "description": "弱ローターなら無限に当てれる説を立証？！絶頂超研究！電マで！バイブで！おしっこも！【バイノーラル、ASMR、フォーリーサウンド、実演音声、実演オナニー】",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_177991/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_177991/d_177991pl.jpg"
  },
  {
    "id": "14",
    "title": "好きなようにおまんこを使わせてくれるクールなお姉ちゃん【バイノーラル】〜お姉ちゃんのまんこオナホ、生でハメてもいーよ〜",
    "circle": "インゴヒゴ",
    "cv": "不明",
    "category": "asmr",
    "price": 1100,
    "rating": 5,
    "tags": [
      "巨乳",
      "中出し",
      "パイズリ",
      "ラブラブ・あまあま",
      "おっぱい",
      "淡白・あっさり"
    ],
    "description": "好きなようにおまんこを使わせてくれるクールなお姉ちゃん【バイノーラル】〜お姉ちゃんのまんこオナホ、生でハメてもいーよ〜",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_168440/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_168440/d_168440pl.jpg"
  },
  {
    "id": "15",
    "title": "清楚で巨乳なお嬢様は臭臭チンポ大好きなおほ声イグイグ妹",
    "circle": "アトリエTODO",
    "cv": "不明",
    "category": "asmr",
    "price": 924,
    "rating": 5,
    "tags": [
      "処女",
      "お嬢様・令嬢",
      "巨乳",
      "中出し",
      "ラブラブ・あまあま",
      "ASMR"
    ],
    "description": "清楚で巨乳なお嬢様は臭臭チンポ大好きなおほ声イグイグ妹",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_638565/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_638565/d_638565pl.jpg"
  },
  {
    "id": "16",
    "title": "【カノ母逆NTR/ドスケベ事後差分イラスト】性欲モンスターな彼女の母親に勃起バレして童貞を喰われる〜シンママとズルズル背徳交尾＆本気射精〜【KU100】",
    "circle": "ろまあぽ",
    "cv": "不明",
    "category": "ntr",
    "price": 1320,
    "rating": 5,
    "tags": [
      "熟女",
      "人妻・主婦",
      "寝取り・寝取られ・NTR",
      "中出し",
      "フェラ",
      "退廃・背徳・インモラル"
    ],
    "description": "【カノ母逆NTR/ドスケベ事後差分イラスト】性欲モンスターな彼女の母親に勃起バレして童貞を喰われる〜シンママとズルズル背徳交尾＆本気射精〜【KU100】",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_635198/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_635198/d_635198pl.jpg"
  },
  {
    "id": "17",
    "title": "アナル大好き！オタクに優しい黒田さんASMR【KU100】",
    "circle": "アトリエTODO",
    "cv": "不明",
    "category": "asmr",
    "price": 770,
    "rating": 5,
    "tags": [
      "巨乳",
      "中出し",
      "アナル",
      "ASMR",
      "KU100",
      "初体験"
    ],
    "description": "アナル大好き！オタクに優しい黒田さんASMR【KU100】",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_537828/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_537828/d_537828pl.jpg"
  },
  {
    "id": "18",
    "title": "【白目を剥いて意識が遠のく！？】18時間超！！舌先に脳が翻弄される★耳舐めライフが止マラんッ！【KU100】",
    "circle": "来世猫と未来の大富豪",
    "cv": "不明",
    "category": "asmr",
    "price": 1320,
    "rating": 5,
    "tags": [
      "萌え",
      "癒し",
      "ASMR",
      "VTuber",
      "汁/液大量"
    ],
    "description": "【白目を剥いて意識が遠のく！？】18時間超！！舌先に脳が翻弄される★耳舐めライフが止マラんッ！【KU100】",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_534090/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_534090/d_534090pl.jpg"
  },
  {
    "id": "19",
    "title": "【超密着×むちむちJK】ローションロッカー部【フォーリーサウンド】",
    "circle": "うえぶんり",
    "cv": "不明",
    "category": "asmr",
    "price": 1320,
    "rating": 5,
    "tags": [
      "学園もの",
      "中出し",
      "ローション・オイル",
      "おっぱい",
      "ASMR",
      "ささやき"
    ],
    "description": "【超密着×むちむちJK】ローションロッカー部【フォーリーサウンド】",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_348616/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_348616/d_348616pl.jpg"
  },
  {
    "id": "20",
    "title": "【4Kぬるぬるアニメ】JK秘密の援○交際",
    "circle": "究極のあいどる",
    "cv": "不明",
    "category": "ntr",
    "price": 165,
    "rating": 5,
    "tags": [
      "動画・アニメーション",
      "音声付き",
      "寝取り・寝取られ・NTR",
      "中出し",
      "退廃・背徳・インモラル",
      "売春・援交"
    ],
    "description": "【4Kぬるぬるアニメ】JK秘密の援○交際",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_302902/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/cg/d_302902/d_302902pl.jpg"
  },
  {
    "id": "21",
    "title": "好感度カンストの後輩JKと大会前の部室でトロ甘耳舐めえっち",
    "circle": "こんふぉ〜たぶる",
    "cv": "不明",
    "category": "asmr",
    "price": 231,
    "rating": 5,
    "tags": [
      "処女",
      "巨乳",
      "フェラ",
      "パイズリ",
      "ラブラブ・あまあま",
      "おっぱい"
    ],
    "description": "好感度カンストの後輩JKと大会前の部室でトロ甘耳舐めえっち",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_300347/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_300347/d_300347pl.jpg"
  },
  {
    "id": "22",
    "title": "【実演】素人リアルオナニー みかこ28歳OL",
    "circle": "DDP",
    "cv": "不明",
    "category": "asmr",
    "price": 385,
    "rating": 5,
    "tags": [
      "OL",
      "巨乳",
      "オナニー",
      "おもちゃ",
      "ノンフィクション・体験談",
      "おっぱい"
    ],
    "description": "【実演】素人リアルオナニー みかこ28歳OL",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_292929/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_292929/d_292929pl.jpg"
  },
  {
    "id": "23",
    "title": "SNSで知り合った清楚な弓道部JKに一生懸命舐められて優しく筆おろしされました♪【cv:みもりあいの】",
    "circle": "Otozock",
    "cv": "不明",
    "category": "asmr",
    "price": 924,
    "rating": 5,
    "tags": [
      "制服",
      "処女",
      "中出し",
      "フェラ",
      "パイズリ",
      "ASMR"
    ],
    "description": "SNSで知り合った清楚な弓道部JKに一生懸命舐められて優しく筆おろしされました♪【cv:みもりあいの】",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_281244/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_281244/d_281244pl.jpg"
  },
  {
    "id": "24",
    "title": "凛堂さや出会って3秒",
    "circle": "「FANZA同人」×「VIRTUAL Live Chat」コラボ",
    "cv": "不明",
    "category": "asmr",
    "price": 550,
    "rating": 5,
    "tags": [
      "痴女",
      "ごっくん",
      "ASMR",
      "バイノーラル",
      "ささやき"
    ],
    "description": "凛堂さや出会って3秒",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_222634/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_222634/d_222634pl.jpg"
  },
  {
    "id": "25",
    "title": "JKたちのアオイ春 -陽キャ処女とあなたの恋の行方-",
    "circle": "制服days（旧：甘声）",
    "cv": "不明",
    "category": "asmr",
    "price": 770,
    "rating": 5,
    "tags": [
      "制服",
      "学園もの",
      "ラブコメ",
      "巨乳",
      "中出し",
      "耳かき"
    ],
    "description": "JKたちのアオイ春 -陽キャ処女とあなたの恋の行方-",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_504251/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_504251/d_504251pl.jpg"
  },
  {
    "id": "26",
    "title": "どすけべ妖艶ムチムチ爆乳きつねお姉さんと濃厚イチャらぶ新コン生活〜ねっとりのじゃボイスで甘えてくる肉食嫁〜",
    "circle": "CRAVEALL",
    "cv": "不明",
    "category": "asmr",
    "price": 1650,
    "rating": 5,
    "tags": [
      "巨乳",
      "ぽっちゃり",
      "和服・浴衣",
      "中出し",
      "フェラ",
      "パイズリ"
    ],
    "description": "どすけべ妖艶ムチムチ爆乳きつねお姉さんと濃厚イチャらぶ新コン生活〜ねっとりのじゃボイスで甘えてくる肉食嫁〜",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_206243/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_206243/d_206243pl.jpg"
  },
  {
    "id": "27",
    "title": "欲求不満な耳かき屋さん 〜あなたの全てをカキ出す禁断ご奉仕SEX【KU100・特典トラック付き】",
    "circle": "あぶそりゅ〜と",
    "cv": "不明",
    "category": "asmr",
    "price": 100,
    "rating": 5,
    "tags": [
      "中出し",
      "フェラ",
      "おっぱい",
      "耳かき",
      "バイノーラル",
      "耳舐め"
    ],
    "description": "欲求不満な耳かき屋さん 〜あなたの全てをカキ出す禁断ご奉仕SEX【KU100・特典トラック付き】",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_243593/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_243593/d_243593pl.jpg"
  },
  {
    "id": "28",
    "title": "元気娘幼馴染の耳かき耳フー耳舐めリラクゼーション〜お疲れ様かな？私が癒してあげる〜",
    "circle": "加速えっぢ",
    "cv": "不明",
    "category": "asmr",
    "price": 1320,
    "rating": 5,
    "tags": [
      "全年齢向け",
      "制服",
      "幼なじみ",
      "ラブラブ・あまあま",
      "純愛",
      "萌え"
    ],
    "description": "元気娘幼馴染の耳かき耳フー耳舐めリラクゼーション〜お疲れ様かな？私が癒してあげる〜",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_215960/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_215960/d_215960pl.jpg"
  },
  {
    "id": "29",
    "title": "ぐにゅぐにゅ舌筋耳舐めリフレ 〜みっちり凝縮舌圧エッチ〜",
    "circle": "すたぁぱれっと",
    "cv": "不明",
    "category": "asmr",
    "price": 1100,
    "rating": 5,
    "tags": [
      "中出し",
      "フェラ",
      "ラブラブ・あまあま",
      "おっぱい",
      "癒し",
      "耳かき"
    ],
    "description": "ぐにゅぐにゅ舌筋耳舐めリフレ 〜みっちり凝縮舌圧エッチ〜",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_190423/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_190423/d_190423pl.jpg"
  },
  {
    "id": "30",
    "title": "《耳舐めASMR》耳癒妖精風俗〜スライムのヌルヌル耳舐めまわしプレイ♪【バイノーラル/ハイレゾ】",
    "circle": "しゅしょく",
    "cv": "不明",
    "category": "asmr",
    "price": 924,
    "rating": 5,
    "tags": [
      "ファンタジー",
      "巨乳",
      "風俗・ソープ",
      "癒し",
      "エルフ・妖精",
      "人外娘・モンスター娘"
    ],
    "description": "《耳舐めASMR》耳癒妖精風俗〜スライムのヌルヌル耳舐めまわしプレイ♪【バイノーラル/ハイレゾ】",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_148115/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_148115/d_148115pl.jpg"
  },
  {
    "id": "31",
    "title": "JKリフレで癒してあげたい 〜慈恵女学院おじさん大好き部〜",
    "circle": "調教少女",
    "cv": "不明",
    "category": "asmr",
    "price": 1100,
    "rating": 5,
    "tags": [
      "制服",
      "処女",
      "ラブラブ・あまあま",
      "純愛",
      "萌え",
      "癒し"
    ],
    "description": "JKリフレで癒してあげたい 〜慈恵女学院おじさん大好き部〜",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_109068/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_109068/d_109068pl.jpg"
  },
  {
    "id": "32",
    "title": "キスしないと好きになる一週間",
    "circle": "ベレス解部",
    "cv": "不明",
    "category": "asmr",
    "price": 1430,
    "rating": 5,
    "tags": [
      "デモ・体験版あり",
      "制服",
      "ニーソックス",
      "中出し",
      "ラブラブ・あまあま",
      "脚"
    ],
    "description": "キスしないと好きになる一週間",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_220737/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_220737/d_220737pl.jpg"
  },
  {
    "id": "33",
    "title": "【低音オホ声】クールで男前な執事は腹の底からゴリゴリオホる。 低音オホッ！ 下品オホッ！ 獣オホッ！",
    "circle": "ふわふわ将軍",
    "cv": "不明",
    "category": "asmr",
    "price": 924,
    "rating": 5,
    "tags": [
      "巨乳",
      "中出し",
      "フェラ",
      "アナル",
      "おっぱい",
      "癒し"
    ],
    "description": "【低音オホ声】クールで男前な執事は腹の底からゴリゴリオホる。 低音オホッ！ 下品オホッ！ 獣オホッ！",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_269959/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_269959/d_269959pl.jpg"
  },
  {
    "id": "34",
    "title": "【KU100】バブみ○○○で甘々サンドイッチ♪ デカパイお姉さん2人組からのバブバブご奉仕♪",
    "circle": "Deep；Dahlia",
    "cv": "不明",
    "category": "asmr",
    "price": 1650,
    "rating": 5,
    "tags": [
      "中出し",
      "3P・4P",
      "ハーレム",
      "ラブラブ・あまあま",
      "おっぱい",
      "耳舐め"
    ],
    "description": "【KU100】バブみ○○○で甘々サンドイッチ♪ デカパイお姉さん2人組からのバブバブご奉仕♪",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_704429/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_704429/d_704429pl.jpg"
  },
  {
    "id": "35",
    "title": "12大特典【寝れるスケベ音声】ゆるふわお姉さんと超密着×全肯定スローH〜寝かしつけからバブバブ搾乳、耳責め騎乗位、夢の中左右同時添い寝まで〜",
    "circle": "スタジオスモーク",
    "cv": "不明",
    "category": "asmr",
    "price": 1155,
    "rating": 5,
    "tags": [
      "処女",
      "巨乳",
      "中出し",
      "フェラ",
      "ラブラブ・あまあま",
      "耳舐め"
    ],
    "description": "12大特典【寝れるスケベ音声】ゆるふわお姉さんと超密着×全肯定スローH〜寝かしつけからバブバブ搾乳、耳責め騎乗位、夢の中左右同時添い寝まで〜",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_656123/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_656123/d_656123pl.jpg"
  },
  {
    "id": "36",
    "title": "【全編ゆるオホ】嗅ぎあね クールな義理姉×2は俺だけに発情する",
    "circle": "しゃーぷ",
    "cv": "不明",
    "category": "asmr",
    "price": 1320,
    "rating": 5,
    "tags": [
      "中出し",
      "オナニー",
      "3P・4P",
      "義姉",
      "ささやき",
      "淫語"
    ],
    "description": "【全編ゆるオホ】嗅ぎあね クールな義理姉×2は俺だけに発情する",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_393356/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_393356/d_393356pl.jpg"
  },
  {
    "id": "37",
    "title": "【KU100/浅木式】助けた奴●エルフに死ぬまで Hで恩返しされるASMR",
    "circle": "いほーじん",
    "cv": "不明",
    "category": "asmr",
    "price": 462,
    "rating": 5,
    "tags": [
      "ファンタジー",
      "処女",
      "巨乳",
      "中出し",
      "おっぱい",
      "エルフ・妖精"
    ],
    "description": "【KU100/浅木式】助けた奴●エルフに死ぬまで Hで恩返しされるASMR",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_274176/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_274176/d_274176pl.jpg"
  },
  {
    "id": "38",
    "title": "【KU100】超密着プリンセスの吐息アクメ 〜言葉にならないウィスパーボイスを耳元で♪〜",
    "circle": "スタジオりふれぼ",
    "cv": "不明",
    "category": "asmr",
    "price": 1320,
    "rating": 5,
    "tags": [
      "お姫様",
      "中出し",
      "フェラ",
      "ラブラブ・あまあま",
      "おっぱい",
      "金髪"
    ],
    "description": "【KU100】超密着プリンセスの吐息アクメ 〜言葉にならないウィスパーボイスを耳元で♪〜",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_240996/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_240996/d_240996pl.jpg"
  },
  {
    "id": "39",
    "title": "Cure Nipple〜乳首責め風俗店で経験豊富な人妻さんに骨抜きにされる〜",
    "circle": "ディーブルスト",
    "cv": "不明",
    "category": "asmr",
    "price": 110,
    "rating": 5,
    "tags": [
      "人妻・主婦",
      "巨乳",
      "ラブラブ・あまあま",
      "風俗・ソープ",
      "おっぱい",
      "癒し"
    ],
    "description": "Cure Nipple〜乳首責め風俗店で経験豊富な人妻さんに骨抜きにされる〜",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_234811/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_234811/d_234811pl.jpg"
  },
  {
    "id": "40",
    "title": "お屋敷メイドのお楽しみBOX 即抜きショート音声＋じっくり癒し音声",
    "circle": "DL製作班",
    "cv": "不明",
    "category": "asmr",
    "price": 990,
    "rating": 5,
    "tags": [
      "メイド",
      "オナニー",
      "萌え",
      "癒し"
    ],
    "description": "お屋敷メイドのお楽しみBOX 即抜きショート音声＋じっくり癒し音声",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_164744/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_164744/d_164744pl.jpg"
  },
  {
    "id": "41",
    "title": "【ALL無声音】フル勃起でバニーの発情トロマンに生ハメしたまま寝れますか？【スローセックス/ずっと生ハメ】",
    "circle": "バブバブの森",
    "cv": "不明",
    "category": "asmr",
    "price": 1320,
    "rating": 5,
    "tags": [
      "バニーガール",
      "中出し",
      "3P・4P",
      "ラブラブ・あまあま",
      "おっぱい",
      "言葉責め"
    ],
    "description": "【ALL無声音】フル勃起でバニーの発情トロマンに生ハメしたまま寝れますか？【スローセックス/ずっと生ハメ】",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_368348/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_368348/d_368348pl.jpg"
  },
  {
    "id": "42",
    "title": "【？？催●解除なし？？】永・久・催・眠【廃人決定】",
    "circle": "空心菜館",
    "cv": "不明",
    "category": "hypno",
    "price": 1320,
    "rating": 5,
    "tags": [
      "中出し",
      "オナニー",
      "言葉責め",
      "耳舐め",
      "ささやき",
      "淫語"
    ],
    "description": "【？？催●解除なし？？】永・久・催・眠【廃人決定】",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_559621/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_559621/d_559621pl.jpg"
  },
  {
    "id": "43",
    "title": "クールな女探偵の胸と尻のせいで仕事に集中できない助手くんの話【1時間/バイノーラル/ラバースーツ】",
    "circle": "巨乳大好き屋",
    "cv": "不明",
    "category": "asmr",
    "price": 77,
    "rating": 5,
    "tags": [
      "処女",
      "巨乳",
      "中出し",
      "フェラ",
      "アナル",
      "ごっくん"
    ],
    "description": "クールな女探偵の胸と尻のせいで仕事に集中できない助手くんの話【1時間/バイノーラル/ラバースーツ】",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_731882/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_731882/d_731882pl.jpg"
  },
  {
    "id": "44",
    "title": "タテマエ？ホンネ！？",
    "circle": "人生通行止め",
    "cv": "不明",
    "category": "ntr",
    "price": 1078,
    "rating": 5,
    "tags": [
      "巨乳",
      "寝取り・寝取られ・NTR",
      "フェラ",
      "恋人同士",
      "寝取らせ"
    ],
    "description": "タテマエ？ホンネ！？",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_422729/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_422729/d_422729pl.jpg"
  },
  {
    "id": "45",
    "title": "監獄より響くオホ声 〜囚われの女騎士がロリっ娘拷問官に屈服するまで〜",
    "circle": "天源高野",
    "cv": "不明",
    "category": "ntr",
    "price": 693,
    "rating": 5,
    "tags": [
      "辱め",
      "羞恥",
      "巨乳",
      "寝取り・寝取られ・NTR",
      "監禁",
      "縛り・緊縛"
    ],
    "description": "監獄より響くオホ声 〜囚われの女騎士がロリっ娘拷問官に屈服するまで〜",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_245179/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_245179/d_245179pl.jpg"
  },
  {
    "id": "46",
    "title": "寝取らせた彼女がチ◯ポを比べながら浮気報告してくれる音声【寝取られマゾ】",
    "circle": "ぎゃっぷスタジオ",
    "cv": "不明",
    "category": "ntr",
    "price": 770,
    "rating": 5,
    "tags": [
      "寝取り・寝取られ・NTR",
      "オナニー",
      "言葉責め"
    ],
    "description": "寝取らせた彼女がチ◯ポを比べながら浮気報告してくれる音声【寝取られマゾ】",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_192573/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_192573/d_192573pl.jpg"
  },
  {
    "id": "47",
    "title": "ラブホ女子会で二人がけ催● 友達の前で連続メスイキアクメするあなた",
    "circle": "しりあるヒプノ",
    "cv": "不明",
    "category": "ts",
    "price": 1430,
    "rating": 5,
    "tags": [
      "音声付き",
      "クンニ",
      "女装・男の娘",
      "百合",
      "言葉責め",
      "コミケ97（2019冬）"
    ],
    "description": "ラブホ女子会で二人がけ催● 友達の前で連続メスイキアクメするあなた",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_165175/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_165175/d_165175pl.jpg"
  },
  {
    "id": "48",
    "title": "Vぬき！AVTuber35名がえっちな声で攻めて癒してヌキヌキしちゃう【withny×FANZA同人限定オリジナル】",
    "circle": "withny×FANZA同人",
    "cv": "不明",
    "category": "asmr",
    "price": 990,
    "rating": 5,
    "tags": [
      "人妻・主婦",
      "フェラ",
      "オナニー",
      "ラブラブ・あまあま",
      "ASMR",
      "サキュバス/淫魔"
    ],
    "description": "Vぬき！AVTuber35名がえっちな声で攻めて癒してヌキヌキしちゃう【withny×FANZA同人限定オリジナル】",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_430369/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_430369/d_430369pl.jpg"
  },
  {
    "id": "49",
    "title": "【TS百合】乳首の快楽でメス堕ちしたあなたが処女をお姉様に捧げる時【メスイキドライセオリー】",
    "circle": "ユビノタクト",
    "cv": "不明",
    "category": "ts",
    "price": 1210,
    "rating": 5,
    "tags": [
      "性転換・女体化",
      "女装・男の娘",
      "レズビアン",
      "アナル",
      "百合",
      "乳首・乳輪"
    ],
    "description": "【TS百合】乳首の快楽でメス堕ちしたあなたが処女をお姉様に捧げる時【メスイキドライセオリー】",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_221160/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_221160/d_221160pl.jpg"
  },
  {
    "id": "50",
    "title": "【実演】イグイグぅっ！ガチイキ連続60分！！絶頂ベスト！！！",
    "circle": "みにょって",
    "cv": "不明",
    "category": "yuri",
    "price": 990,
    "rating": 5,
    "tags": [
      "痴女",
      "人妻・主婦",
      "巨乳",
      "オナニー",
      "百合",
      "ASMR"
    ],
    "description": "【実演】イグイグぅっ！ガチイキ連続60分！！絶頂ベスト！！！",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_216924/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_216924/d_216924pl.jpg"
  },
  {
    "id": "51",
    "title": "3姉妹シェアハウス 大家さんは共用部に含まれます！",
    "circle": "＋ ucca ∫ ucca ＋",
    "cv": "不明",
    "category": "asmr",
    "price": 1540,
    "rating": 5,
    "tags": [
      "ハーレム",
      "ラブラブ・あまあま",
      "萌え",
      "バイノーラル"
    ],
    "description": "3姉妹シェアハウス 大家さんは共用部に含まれます！",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_212170/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_212170/d_212170pl.jpg"
  },
  {
    "id": "52",
    "title": "15日間オナニーのことばかり考えてました！1週間オナ充！1週間オナ禁！最終日は大暴走オナニー！【バイノーラル、ASMR、フォーリーサウンド、実演音声、実演オナニー】",
    "circle": "ぼっちえっちLAB",
    "cv": "不明",
    "category": "asmr",
    "price": 924,
    "rating": 5,
    "tags": [
      "音声付き",
      "デモ・体験版あり",
      "巨乳",
      "野外・露出",
      "フェラ",
      "バイブ"
    ],
    "description": "15日間オナニーのことばかり考えてました！1週間オナ充！1週間オナ禁！最終日は大暴走オナニー！【バイノーラル、ASMR、フォーリーサウンド、実演音声、実演オナニー】",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_180178/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_180178/d_180178pl.jpg"
  },
  {
    "id": "53",
    "title": "姉妹の精神的キメセク催● 倒錯的特殊性交事情 -ザッピングシステム搭載- （男女共用）",
    "circle": "しりあるヒプノ",
    "cv": "不明",
    "category": "ts",
    "price": 1430,
    "rating": 5,
    "tags": [
      "性転換・女体化",
      "巨乳",
      "中出し",
      "フェラ",
      "ぶっかけ",
      "アナル"
    ],
    "description": "姉妹の精神的キメセク催● 倒錯的特殊性交事情 -ザッピングシステム搭載- （男女共用）",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_158636/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_158636/d_158636pl.jpg"
  },
  {
    "id": "54",
    "title": "『女体快楽実験場』 被験体No，009「もぶA」Stage，1前編",
    "circle": "OHOGOE",
    "cv": "不明",
    "category": "asmr",
    "price": 330,
    "rating": 5,
    "tags": [
      "オナニー",
      "放尿・お漏らし",
      "おもらし",
      "アヘ顔",
      "淫語",
      "初体験"
    ],
    "description": "『女体快楽実験場』 被験体No，009「もぶA」Stage，1前編",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_674766/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_674766/d_674766pl.jpg"
  },
  {
    "id": "55",
    "title": "10年ぶりに再会した幼馴染姉妹と濃厚どっぷり種付けセックス♪",
    "circle": "アルファートリル",
    "cv": "不明",
    "category": "asmr",
    "price": 1320,
    "rating": 5,
    "tags": [
      "音声付き",
      "デモ・体験版あり",
      "幼なじみ",
      "中出し",
      "フェラ",
      "パイズリ"
    ],
    "description": "10年ぶりに再会した幼馴染姉妹と濃厚どっぷり種付けセックス♪",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_147851/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_147851/d_147851pl.jpg"
  },
  {
    "id": "56",
    "title": "【160分】過保護なオホ声シスターは主様に中出しされたい【吐息/潮吹き】",
    "circle": "バブバブの森",
    "cv": "不明",
    "category": "asmr",
    "price": 1078,
    "rating": 5,
    "tags": [
      "シスター",
      "巨乳",
      "野外・露出",
      "中出し",
      "フェラ",
      "3P・4P"
    ],
    "description": "【160分】過保護なオホ声シスターは主様に中出しされたい【吐息/潮吹き】",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_244642/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_244642/d_244642pl.jpg"
  },
  {
    "id": "57",
    "title": "学園催●調教記録 〜高飛車お嬢様のむっつりスケベなロイヤルボディをドスケベ肉便器化〜",
    "circle": "四風の街",
    "cv": "不明",
    "category": "asmr",
    "price": 1430,
    "rating": 5,
    "tags": [
      "音声付き",
      "デモ・体験版あり",
      "処女",
      "お嬢様・令嬢",
      "学園もの",
      "巨乳"
    ],
    "description": "学園催●調教記録 〜高飛車お嬢様のむっつりスケベなロイヤルボディをドスケベ肉便器化〜",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_184555/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_184555/d_184555pl.jpg"
  },
  {
    "id": "58",
    "title": "【実演オナニー】超待望の作品デビュー！！総フォロワー数7万超え音声系裏アカ女子「めるち」さん！！バイブ出し入れハメ潮吹きながら25回以上絶頂！！【オホ声の才能】",
    "circle": "実演オホ声",
    "cv": "不明",
    "category": "asmr",
    "price": 440,
    "rating": 5,
    "tags": [
      "オナニー",
      "おもちゃ",
      "ノンフィクション・体験談",
      "連続絶頂",
      "潮吹き",
      "オホ声"
    ],
    "description": "【実演オナニー】超待望の作品デビュー！！総フォロワー数7万超え音声系裏アカ女子「めるち」さん！！バイブ出し入れハメ潮吹きながら25回以上絶頂！！【オホ声の才能】",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_485114/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_485114/d_485114pl.jpg"
  },
  {
    "id": "59",
    "title": "大王様と後宮の女達-ハメ放題！脳がバグるほど気持ちいい三方向快感ヘブン！朝も昼も夜も欲しがる女達とヤリまくり！",
    "circle": "ふぃーるあっぷ♪",
    "cv": "不明",
    "category": "asmr",
    "price": 1320,
    "rating": 5,
    "tags": [
      "ファンタジー",
      "乱交",
      "中出し",
      "3P・4P",
      "ハーレム",
      "ラブラブ・あまあま"
    ],
    "description": "大王様と後宮の女達-ハメ放題！脳がバグるほど気持ちいい三方向快感ヘブン！朝も昼も夜も欲しがる女達とヤリまくり！",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_250236/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_250236/d_250236pl.jpg"
  },
  {
    "id": "60",
    "title": "弟大好きな変態お姉ちゃんの、朝昼晩オナサポっ♪",
    "circle": "ダチュラスクリプト",
    "cv": "不明",
    "category": "asmr",
    "price": 770,
    "rating": 5,
    "tags": [
      "音声付き",
      "デモ・体験版あり",
      "痴女",
      "巨乳",
      "中出し",
      "フェラ"
    ],
    "description": "弟大好きな変態お姉ちゃんの、朝昼晩オナサポっ♪",
    "affiliateUrl": "https://www.dmm.co.jp/dc/doujin/-/detail/=/cid=d_161765/",
    "thumbnailUrl": "https://doujin-assets.dmm.co.jp/digital/voice/d_161765/d_161765pl.jpg"
  }
];

export function getWorkById(id: string): Work | undefined {
  return works.find((w) => w.id === id);
}

export function getWorksByCategory(category: Category): Work[] {
  return works.filter((w) => w.category === category);
}

export function getAllTags(): string[] {
  const tags = new Set<string>();
  works.forEach((w) => w.tags.forEach((t) => tags.add(t)));
  return Array.from(tags).sort();
}

export function getWorksByTag(tag: string): Work[] {
  return works.filter((w) => w.tags.includes(tag));
}

export function getTopWorks(limit = 10): Work[] {
  return [...works].sort((a, b) => b.rating - a.rating).slice(0, limit);
}

export function getPickupWork(): Work | undefined {
  return works.find((w) => w.rating >= 4.5) ?? works[0];
}
